name: 'doc-check'
description: 'Automatic Documentation Consistency Checker'
author: 'Alex Vukadinov'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'book-open'
  color: 'yellow'

# Define your inputs here.
inputs:
  openapi-path:
    required: true
  doc-path:
    required: true
  token:
    required: true

runs:
  using: node20
  main: dist/index.js
